//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComponentBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComponentBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gleichung wurde berechnet: .
        /// </summary>
        internal static string LOGGER_CALC_CALC {
            get {
                return ResourceManager.GetString("LOGGER_CALC_CALC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gleichung konnte nicht kopiert werden: .
        /// </summary>
        internal static string LOGGER_CALC_COPY_NE {
            get {
                return ResourceManager.GetString("LOGGER_CALC_COPY_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gleichung wurde erfolgreich kopiert: .
        /// </summary>
        internal static string LOGGER_CALC_COPY_OK {
            get {
                return ResourceManager.GetString("LOGGER_CALC_COPY_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gleichung konnte nicht gelöscht werden: .
        /// </summary>
        internal static string LOGGER_CALC_DEL_NE {
            get {
                return ResourceManager.GetString("LOGGER_CALC_DEL_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gleichung wurde erfolgreich gelöscht: .
        /// </summary>
        internal static string LOGGER_CALC_DEL_OK {
            get {
                return ResourceManager.GetString("LOGGER_CALC_DEL_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gleichung wurde bearbeitet: .
        /// </summary>
        internal static string LOGGER_CALC_EDIT {
            get {
                return ResourceManager.GetString("LOGGER_CALC_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gleichung konnte der Parameter nicht als Input zugewiesen werden: .
        /// </summary>
        internal static string LOGGER_CALC_INP_NE {
            get {
                return ResourceManager.GetString("LOGGER_CALC_INP_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gleichung wurde Input-Parameter zugewiesen: .
        /// </summary>
        internal static string LOGGER_CALC_INP_OK {
            get {
                return ResourceManager.GetString("LOGGER_CALC_INP_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gleichung konnte der Parameter nicht als Output zugewiesen werden: .
        /// </summary>
        internal static string LOGGER_CALC_OUTP_NE {
            get {
                return ResourceManager.GetString("LOGGER_CALC_OUTP_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gleichung wurde Output-Parameter zugewiesen: .
        /// </summary>
        internal static string LOGGER_CALC_OUTP_OK {
            get {
                return ResourceManager.GetString("LOGGER_CALC_OUTP_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Komponente wurden mögliche Funktionen zugewiesen: .
        /// </summary>
        internal static string LOGGER_COMP_ASSIGN_SLOT {
            get {
                return ResourceManager.GetString("LOGGER_COMP_ASSIGN_SLOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponenten-Gleichung wurde gelöscht: .
        /// </summary>
        internal static string LOGGER_COMP_CALC_DEL {
            get {
                return ResourceManager.GetString("LOGGER_COMP_CALC_DEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponetengleichung wird bearbeitet: .
        /// </summary>
        internal static string LOGGER_COMP_CALC_EDIT {
            get {
                return ResourceManager.GetString("LOGGER_COMP_CALC_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter konnte nicht in die Komponentengleichung als Input übernommen werden: .
        /// </summary>
        internal static string LOGGER_COMP_CALC_PI_GET_NE {
            get {
                return ResourceManager.GetString("LOGGER_COMP_CALC_PI_GET_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter wurde in die Komponentengleichung als Input übernommen: .
        /// </summary>
        internal static string LOGGER_COMP_CALC_PI_GET_OK {
            get {
                return ResourceManager.GetString("LOGGER_COMP_CALC_PI_GET_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter konnte nicht in die Komponentengleichung als Output übernommen werden: .
        /// </summary>
        internal static string LOGGER_COMP_CALC_PO_GET_NE {
            get {
                return ResourceManager.GetString("LOGGER_COMP_CALC_PO_GET_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter wurde in die Komponentengleichung als Output übernommen: .
        /// </summary>
        internal static string LOGGER_COMP_CALC_PO_GET_OK {
            get {
                return ResourceManager.GetString("LOGGER_COMP_CALC_PO_GET_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponente konnte nicht kopiert werden: .
        /// </summary>
        internal static string LOGGER_COMP_COPY_NE {
            get {
                return ResourceManager.GetString("LOGGER_COMP_COPY_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponente wurde erfolgreich kopiert: .
        /// </summary>
        internal static string LOGGER_COMP_COPY_OK {
            get {
                return ResourceManager.GetString("LOGGER_COMP_COPY_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die markierten Komponenten wurden gelöscht..
        /// </summary>
        internal static string LOGGER_COMP_DEL_M {
            get {
                return ResourceManager.GetString("LOGGER_COMP_DEL_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponente konnte nicht gelöscht werden: .
        /// </summary>
        internal static string LOGGER_COMP_DEL_NE {
            get {
                return ResourceManager.GetString("LOGGER_COMP_DEL_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponente wurde erfolgreich gelöscht: .
        /// </summary>
        internal static string LOGGER_COMP_DEL_OK {
            get {
                return ResourceManager.GetString("LOGGER_COMP_DEL_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponente wurde  bearbeitet: .
        /// </summary>
        internal static string LOGGER_COMP_EDIT {
            get {
                return ResourceManager.GetString("LOGGER_COMP_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponenten-Parameter wurde innerhalb der Komponente kopiert: .
        /// </summary>
        internal static string LOGGER_COMP_P_COPY {
            get {
                return ResourceManager.GetString("LOGGER_COMP_P_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponentenparameter wurde bearbeitet: .
        /// </summary>
        internal static string LOGGER_COMP_P_EDIT {
            get {
                return ResourceManager.GetString("LOGGER_COMP_P_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter konnte nicht in die Komponente kopiert werden: .
        /// </summary>
        internal static string LOGGER_COMP_P_GET_NE {
            get {
                return ResourceManager.GetString("LOGGER_COMP_P_GET_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter wurde in Komponente kopiert: .
        /// </summary>
        internal static string LOGGER_COMP_P_GET_OK {
            get {
                return ResourceManager.GetString("LOGGER_COMP_P_GET_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konnte nicht als referenzierte Komponente übernommen werden: .
        /// </summary>
        internal static string LOGGER_COMP_REF_NE {
            get {
                return ResourceManager.GetString("LOGGER_COMP_REF_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als referenzierte Komponente übernommen: .
        /// </summary>
        internal static string LOGGER_COMP_REF_OK {
            get {
                return ResourceManager.GetString("LOGGER_COMP_REF_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponente wurde zur Publikation freigegeben: .
        /// </summary>
        internal static string LOGGER_COMP_RELEASE {
            get {
                return ResourceManager.GetString("LOGGER_COMP_RELEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konnte nicht als Subkomponente kopiert werden: .
        /// </summary>
        internal static string LOGGER_COMP_SUB_NE {
            get {
                return ResourceManager.GetString("LOGGER_COMP_SUB_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als Subkomponenten kopiert und übernommen: .
        /// </summary>
        internal static string LOGGER_COMP_SUB_OK {
            get {
                return ResourceManager.GetString("LOGGER_COMP_SUB_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponente wurde freigegeben: .
        /// </summary>
        internal static string LOGGER_COMP_SUPERV {
            get {
                return ResourceManager.GetString("LOGGER_COMP_SUPERV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponente wurde Symbol zugewiesen: .
        /// </summary>
        internal static string LOGGER_COMP_SYMB {
            get {
                return ResourceManager.GetString("LOGGER_COMP_SYMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponente wurde zum Mapping gewählt..
        /// </summary>
        internal static string LOGGER_COMP2COMP_M_PICK_COMP {
            get {
                return ResourceManager.GetString("LOGGER_COMP2COMP_M_PICK_COMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponente wurde zum Mapping auf eine Web-Service ausgewählt: .
        /// </summary>
        internal static string LOGGER_COMP2WS_PICK_COMP {
            get {
                return ResourceManager.GetString("LOGGER_COMP2WS_PICK_COMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponente wurde zum Vergleichen ausgewählt: .
        /// </summary>
        internal static string LOGGER_COMPCOMP_PICK_COMP {
            get {
                return ResourceManager.GetString("LOGGER_COMPCOMP_PICK_COMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbole wurden nach Nummer zugewiesen..
        /// </summary>
        internal static string LOGGER_IMG_SET {
            get {
                return ResourceManager.GetString("LOGGER_IMG_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponenten wurden aus Bibliothek importiert..
        /// </summary>
        internal static string LOGGER_IN_COMP_OK {
            get {
                return ResourceManager.GetString("LOGGER_IN_COMP_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponentensichtbarkeit konnte nicht geladen werden: .
        /// </summary>
        internal static string LOGGER_IN_COMP_VIS_NE {
            get {
                return ResourceManager.GetString("LOGGER_IN_COMP_VIS_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponentensichtbarkeit wurde aus txt-File geladen: .
        /// </summary>
        internal static string LOGGER_IN_COMP_VIS_OK {
            get {
                return ResourceManager.GetString("LOGGER_IN_COMP_VIS_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponentenbibliothek konnte nicht geladen werden: .
        /// </summary>
        internal static string LOGGER_IN_COMPS_NE {
            get {
                return ResourceManager.GetString("LOGGER_IN_COMPS_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponenten und Netzwerke konnten nicht importiert werden: .
        /// </summary>
        internal static string LOGGER_IN_COMPS_NWS_NE {
            get {
                return ResourceManager.GetString("LOGGER_IN_COMPS_NWS_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponenten und Netzwerke wurden aus Bibliothek importiert..
        /// </summary>
        internal static string LOGGER_IN_COMPS_NWS_OK {
            get {
                return ResourceManager.GetString("LOGGER_IN_COMPS_NWS_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponentenbibliothek wurde aus dxf-File geladen: .
        /// </summary>
        internal static string LOGGER_IN_COMPS_OK {
            get {
                return ResourceManager.GetString("LOGGER_IN_COMPS_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelle konnte nicht geladen werden: .
        /// </summary>
        internal static string LOGGER_IN_EXCELT_NE {
            get {
                return ResourceManager.GetString("LOGGER_IN_EXCELT_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelle wurde aus excel-File geladen: .
        /// </summary>
        internal static string LOGGER_IN_EXCELT_OK {
            get {
                return ResourceManager.GetString("LOGGER_IN_EXCELT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild konnte nicht geladen werden: .
        /// </summary>
        internal static string LOGGER_IN_IMG_NE {
            get {
                return ResourceManager.GetString("LOGGER_IN_IMG_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild wurde aus File geladen: .
        /// </summary>
        internal static string LOGGER_IN_IMG_OK {
            get {
                return ResourceManager.GetString("LOGGER_IN_IMG_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildsammlung konnte nicht geladen werden: .
        /// </summary>
        internal static string LOGGER_IN_IMGS_NE {
            get {
                return ResourceManager.GetString("LOGGER_IN_IMGS_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildsammlung wurde aus bin-File geladen: .
        /// </summary>
        internal static string LOGGER_IN_IMGS_OK {
            get {
                return ResourceManager.GetString("LOGGER_IN_IMGS_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kennfeldbibliothek konnte nicht geladen werden: .
        /// </summary>
        internal static string LOGGER_IN_MV_NE {
            get {
                return ResourceManager.GetString("LOGGER_IN_MV_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kennfeldbibliothek aus dxf-File geladen: .
        /// </summary>
        internal static string LOGGER_IN_MV_OK {
            get {
                return ResourceManager.GetString("LOGGER_IN_MV_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameterbibliothek konnte nicht geladen werden: .
        /// </summary>
        internal static string LOGGER_IN_P_NE {
            get {
                return ResourceManager.GetString("LOGGER_IN_P_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameterbibliothek wurde aus dxf-File geladen: .
        /// </summary>
        internal static string LOGGER_IN_P_OK {
            get {
                return ResourceManager.GetString("LOGGER_IN_P_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt konnte nicht geladen werden: .
        /// </summary>
        internal static string LOGGER_IN_PROJ_NE {
            get {
                return ResourceManager.GetString("LOGGER_IN_PROJ_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt wurde aus smn-File geladen: .
        /// </summary>
        internal static string LOGGER_IN_PROJ_OK {
            get {
                return ResourceManager.GetString("LOGGER_IN_PROJ_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netzwerk konnte nicht kopiert werden: .
        /// </summary>
        internal static string LOGGER_NW_COPY_NE {
            get {
                return ResourceManager.GetString("LOGGER_NW_COPY_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netzwerk wurde erfolgreich kopiert: .
        /// </summary>
        internal static string LOGGER_NW_COPY_OK {
            get {
                return ResourceManager.GetString("LOGGER_NW_COPY_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die markierten Netzwerke wurden gelöscht..
        /// </summary>
        internal static string LOGGER_NW_DEL_M {
            get {
                return ResourceManager.GetString("LOGGER_NW_DEL_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netzwerk wurde erstellt: .
        /// </summary>
        internal static string LOGGER_NW_NEW {
            get {
                return ResourceManager.GetString("LOGGER_NW_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dem Netzwerkelement wurde Komponente zugewiesen: .
        /// </summary>
        internal static string LOGGER_NW_PICK_COMP {
            get {
                return ResourceManager.GetString("LOGGER_NW_PICK_COMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponentenbibliothek konnte nicht gespeichert werden: .
        /// </summary>
        internal static string LOGGER_OUT_COMP_NE {
            get {
                return ResourceManager.GetString("LOGGER_OUT_COMP_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponentenbibliothek wurde als dxf-File gespeichert: .
        /// </summary>
        internal static string LOGGER_OUT_COMP_OK {
            get {
                return ResourceManager.GetString("LOGGER_OUT_COMP_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponentensichtbarkeit konnte nicht gespeichert werden: .
        /// </summary>
        internal static string LOGGER_OUT_COMP_VIS_NE {
            get {
                return ResourceManager.GetString("LOGGER_OUT_COMP_VIS_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponentensichtbarkeit wurde als txt-File gespeichert: .
        /// </summary>
        internal static string LOGGER_OUT_COMP_VIS_OK {
            get {
                return ResourceManager.GetString("LOGGER_OUT_COMP_VIS_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildsammlung konnte nicht gespeichert werden: .
        /// </summary>
        internal static string LOGGER_OUT_IMGS_NE {
            get {
                return ResourceManager.GetString("LOGGER_OUT_IMGS_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildsammlung wurde als bin-File gespeichert: .
        /// </summary>
        internal static string LOGGER_OUT_IMGS_OK {
            get {
                return ResourceManager.GetString("LOGGER_OUT_IMGS_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kennfeldbibliothek konnte nicht gespeichert werden: .
        /// </summary>
        internal static string LOGGER_OUT_MV_NE {
            get {
                return ResourceManager.GetString("LOGGER_OUT_MV_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kennfeldbibliothek wurde als dxf-File gespeichert: .
        /// </summary>
        internal static string LOGGER_OUT_MV_OK {
            get {
                return ResourceManager.GetString("LOGGER_OUT_MV_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameterbibliothek konnte nicht gespeichert werden: .
        /// </summary>
        internal static string LOGGER_OUT_P_NE {
            get {
                return ResourceManager.GetString("LOGGER_OUT_P_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameterbibliothek wurde als dxf-File gespeichert: .
        /// </summary>
        internal static string LOGGER_OUT_P_OK {
            get {
                return ResourceManager.GetString("LOGGER_OUT_P_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt wird gespeichert..
        /// </summary>
        internal static string LOGGER_OUT_PROJ {
            get {
                return ResourceManager.GetString("LOGGER_OUT_PROJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt wird gespeichert unter: .
        /// </summary>
        internal static string LOGGER_OUT_PROJ_AS {
            get {
                return ResourceManager.GetString("LOGGER_OUT_PROJ_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt wird geschlossen.
        /// </summary>
        internal static string LOGGER_OUT_PROJ_CL {
            get {
                return ResourceManager.GetString("LOGGER_OUT_PROJ_CL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt wird entsperrt..
        /// </summary>
        internal static string LOGGER_OUT_PROJ_UNLOCK {
            get {
                return ResourceManager.GetString("LOGGER_OUT_PROJ_UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponentenbibliothek konnte nicht in Repository gespeichert werden: .
        /// </summary>
        internal static string LOGGER_OUT_TO_SERVER_COMP_NE {
            get {
                return ResourceManager.GetString("LOGGER_OUT_TO_SERVER_COMP_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponentenbibliothek wurde als dxf-File in Repository gespeichert: .
        /// </summary>
        internal static string LOGGER_OUT_TO_SERVER_COMP_OK {
            get {
                return ResourceManager.GetString("LOGGER_OUT_TO_SERVER_COMP_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter konnte nicht kopiert werden: .
        /// </summary>
        internal static string LOGGER_PARAM_COPY_NE {
            get {
                return ResourceManager.GetString("LOGGER_PARAM_COPY_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter wurde erfolgreich kopiert: .
        /// </summary>
        internal static string LOGGER_PARAM_COPY_OK {
            get {
                return ResourceManager.GetString("LOGGER_PARAM_COPY_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dem Parameter wurde ein Kennfeld zugewiesen: .
        /// </summary>
        internal static string LOGGER_PARAM_COUPLE {
            get {
                return ResourceManager.GetString("LOGGER_PARAM_COUPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter wurde vom Wertefeld entkoppelt..
        /// </summary>
        internal static string LOGGER_PARAM_DECOUPLE_OK {
            get {
                return ResourceManager.GetString("LOGGER_PARAM_DECOUPLE_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Parameter wurden gelöscht..
        /// </summary>
        internal static string LOGGER_PARAM_DEL_ALL_OK {
            get {
                return ResourceManager.GetString("LOGGER_PARAM_DEL_ALL_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter konnte nicht gelöscht werden: .
        /// </summary>
        internal static string LOGGER_PARAM_DEL_NE {
            get {
                return ResourceManager.GetString("LOGGER_PARAM_DEL_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter wurde erfolgreich gelöscht: .
        /// </summary>
        internal static string LOGGER_PARAM_DEL_OK {
            get {
                return ResourceManager.GetString("LOGGER_PARAM_DEL_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter wurde bearbeitet: .
        /// </summary>
        internal static string LOGGER_PARAM_EDIT {
            get {
                return ResourceManager.GetString("LOGGER_PARAM_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kennfeld konnte nicht kopiert werden!.
        /// </summary>
        internal static string LOGGER_VALUE_COPY_NE {
            get {
                return ResourceManager.GetString("LOGGER_VALUE_COPY_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kennfeld wurde erfolgreich kopiert..
        /// </summary>
        internal static string LOGGER_VALUE_COPY_OK {
            get {
                return ResourceManager.GetString("LOGGER_VALUE_COPY_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Kennfelder wurden gelöscht..
        /// </summary>
        internal static string LOGGER_VALUE_DEL_ALL {
            get {
                return ResourceManager.GetString("LOGGER_VALUE_DEL_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kennfeld konnte nicht gelöscht werden!.
        /// </summary>
        internal static string LOGGER_VALUE_DEL_NE {
            get {
                return ResourceManager.GetString("LOGGER_VALUE_DEL_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kennfeld wurde erfolgreich gelöscht..
        /// </summary>
        internal static string LOGGER_VALUE_DEL_OK {
            get {
                return ResourceManager.GetString("LOGGER_VALUE_DEL_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktionsfeld wurde bearbeitet: .
        /// </summary>
        internal static string LOGGER_VALUE_EDIT_F {
            get {
                return ResourceManager.GetString("LOGGER_VALUE_EDIT_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wertefeld wurde bearbeitet: .
        /// </summary>
        internal static string LOGGER_VALUE_EDIT_T {
            get {
                return ResourceManager.GetString("LOGGER_VALUE_EDIT_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Tabelle wurde erstellt..
        /// </summary>
        internal static string LOGGER_VALUE_NEW_BT {
            get {
                return ResourceManager.GetString("LOGGER_VALUE_NEW_BT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Funktionsfeld wurde erstellt..
        /// </summary>
        internal static string LOGGER_VALUE_NEW_F {
            get {
                return ResourceManager.GetString("LOGGER_VALUE_NEW_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Wertefeld wurde erstellt..
        /// </summary>
        internal static string LOGGER_VALUE_NEW_T {
            get {
                return ResourceManager.GetString("LOGGER_VALUE_NEW_T", resourceCulture);
            }
        }
    }
}
